adrian/conf/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from contacts import views as contacts_views

urlpatterns = [
    url(
        r'^admin/',
        include(admin.site.urls)),
    url(
        r'^store/catalog/',
        include('store.catalog.urls')),
    url(
        r'^store/cart/',
        include('store.cart.urls')),
    url(
        r'^contacts$',
        contacts_views.contacts,
        name='contacts'),
    url(
        r'^services$',
        TemplateView.as_view(template_name='pages/services.html'),
        name='services'),
    url(
        r'^price$',
        TemplateView.as_view(template_name='pages/price.html'),
        name='price'),
    url(
        r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adrian/store/cart/urls.py
__author__ = 'Dmitriy'
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache

from store.cart import views

urlpatterns = [
    url(r'^cartPreview$',
        never_cache(views.cart_preview),
        name='cart_preview'),
    url(r'^checkout$',
        never_cache(views.CheckoutView.as_view()),
        name='cart_checkout'),
    url(r'^checkout/success$',
        never_cache(views.CheckoutSuccessView.as_view()),
        name='checkout_success')
]

adrian/store/catalog/urls.py
__author__ = 'Dmitriy'

from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from store.catalog.views import ItemDetailView, ItemListView

urlpatterns = [
    url(r'^category/(?P<category_id>\d+)$', cache_page(60 * 30)(ItemListView.as_view()), name='items_in_category'),
    url(r'^item/(?P<pk>\d+)$', cache_page(60 * 30)(ItemDetailView.as_view()), name='item_page')
]

adrian/rt_models/models.py
import os
import inspect
import importlib
from django.apps import apps
from django.conf import settings
from django.core.management import execute_from_command_line
from django.db import models


def get_sourcecode_filename():
    return getattr(settings, 'RT_MODELS_PATH', 'rt_models.py')


def get_sourcecode_path(app_name):
    """
    Place to store runtime generated models
    :param app_name:
    :return:
    """
    filename = get_sourcecode_filename()
    return os.path.join(
        os.path.dirname(os.path.normpath(os.sys.modules[app_name].__file__)),
        filename)


def apply_to_db():
    """
    Apply registered models to db (generate migrations and apply them)
    :return:
    """
    execute_from_command_line(['manage.py', 'makemigrations'])
    execute_from_command_line(['manage.py', 'migrate'])


def reg_model_python(model, touch_db=False):
    """
    Register new model using created type object
    :param model: Model to register
    :param touch_db: If true database will be changed immediately
    :return:
    """
    try:
        apps.get_registered_model(model._meta.app_label, model._meta.object_name)
    except LookupError:
        apps.register_model(model._meta.app_label, model)
    with open(get_sourcecode_path(model._meta.app_label), 'a') as f:
        f.writelines(inspect.getsource(model))
    if touch_db:
        apply_to_db()


def reg_model_attrs(model_name, app_label, attrs, base_models=(models.Model,)):
    """
    Register new model using dict of attrs.
    Example:
        reg_model_from_attrs(
            'Person',
            {
                'name': models.CharField(max_length=32),
                '__module__': 'myapp.models'
            }
        )

    :param model_name: Name of model class
    :param base_model: Base model for new runtime model.
    :param attrs: Info about model.
    :return:
    """
    model = type(model_name, (base_models,), attrs)
    model._meta.app_label = app_label
    reg_model_python(model)


def get_rt_model(app_label, model_name):
    return apps.get_model(app_label, model_name)


def import_rt_models():
    raise NotImplementedError
    # This will return a list of frame records, [1] is the frame
    # record of the caller.
    frame_records = inspect.stack()[1]
    # Index 1 of frame_records is the full path of the module,
    # we can then use inspect.getmodulename() to get the
    # module name from this path.
    calling_module = inspect.getmodulename(frame_records[1])
    importlib.import_module('.{0}'.format(get_sourcecode_filename()), calling_module)

adrian/slideshows/models.py
__author__ = 'Dmitriy'

from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField


class Slideshow(models.Model):
    name = models.CharField(max_length=50, unique=True)


class Slide(models.Model):
    label = models.CharField(max_length=50, blank=True)
    description = models.CharField(max_length=50, blank=True)
    image = ThumbnailerImageField(upload_to='media/images/slides')
    slideshow = models.ForeignKey(Slideshow)

adrian/store/cart/models.py
import collections
import json
from decimal import *
from urllib import parse

from django.db import models

from store.catalog.models import Modification


def get_price(modification):
    ''' (models.Modification) -> models.Characteristic
    Get price from database for modification.
    '''
    return modification.get_characteristic_by_name('price')


# Represents product in cart
class Product:
    def __init__(self, modification, count):
        '''
        :param modification: Some modification is a product in cart
        :param count: Count of products
        :type modification: models.Modification
        :type count: int
        '''
        self.modification = modification
        self.count = count
        price = get_price(modification)
        self.price = price.value
        self.unit = price.unit()
        self.__calc_total_price()

    def __calc_total_price(self):
        self.total_price = Decimal(self.price) * Decimal(self.count)


# Represents cart
class ProductsCart:
    cookie_name = 'products_in_cart'

    @staticmethod
    def parse_from_request(request):
        cookies = request.COOKIES.get(ProductsCart.cookie_name)
        if not cookies:
            return ProductsCart()
        products_in_cookies = json.loads(parse.unquote(cookies))
        if products_in_cookies:
            return ProductsCart(source=products_in_cookies.items())
        else:
            return ProductsCart()

    @staticmethod
    def clear_in_response(response):
        response.delete_cookie(ProductsCart.cookie_name)

    def __init__(self, source=None, **kwargs):
        '''
        :param source: Source to initialize
        :type source: Iterable, each cell of which is ('modification id', 'count in cart')
        '''
        self.products = []
        self.bad_products = [] # Products which are missing in database (maybe removed)
        self.total_price = Decimal(0)
        if source is not None:
            for mod_id, ct in source:
                mod = Modification.objects.get(id=mod_id)
                if mod is None:
                    self.bad_products.append({'id': mod_id, 'ct': ct})
                else:
                    self.add_product(Product(mod, ct))

    def add_product(self, product):
        '''
        Add product to cart and recalculate total_price
        :type product: Product
        '''
        self.products.append(product)
        self.total_price += product.total_price

    def get_total_price_unit(self):
        if len(self.products) > 0:
            return self.products[0].unit
        else:
            return None

    def __iter__(self):
        return iter(self.products)

    def __len__(self):
        return len(self.products)

    def __nonzero__(self):
        return self.products.__nonzero__()

adrian/store/catalog/models.py
__author__ = 'Dmitriy'
from django.core import validators
from django.db import models
from django.db.models import signals, ExpressionWrapper, F
from django.dispatch import receiver
from easy_thumbnails.fields import ThumbnailerImageField


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='Название категории',
        unique='true')

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='Имя',
        unique='true')
    description = models.TextField(
        verbose_name='Описание')
    category = models.ForeignKey(
        Category,
        verbose_name='Категория')

    def __str__(self):
        return self.name

    # Returns first related image
    def main_image(self):
        return self.itemimage_set.all()[0]

    def get_price_range(self):
        """
        Get price range (f.e. 100 rub. - 300 rub.)
        :return: {'low':Decimal, 'hight':Decimal, 'field_type':FieldType of price}
        """
        try:
            price_field_type = FieldType.objects.get(
                name='price',
                category=self.category
            )
            res = Characteristic.objects\
                .filter(
                    field_type=price_field_type,
                    modification__item=self
                )\
                .annotate(
                    price_decimal=ExpressionWrapper(
                        F('value'),
                        output_field=models.DecimalField()
                    )
                )\
                .aggregate(
                    low=models.Min('price_decimal'),
                    hight=models.Max('price_decimal')
                )
            res['field_type'] = price_field_type
            return res
        except models.ObjectDoesNotExist:
            return None


class ItemImage(models.Model):
    item = models.ForeignKey(Item)
    image = ThumbnailerImageField(
        upload_to='images/store',
        validators=[validators.RegexValidator(
            regex=r'^[\x00-\x7F]+$',
            message="Only ascii characters can be used")])


class Modification(models.Model):
    name = models.CharField(max_length=50)
    item = models.ForeignKey(Item)

    def __str__(self):
        return self.name

    def get_field_value(self, field_type):
        try:
            return Characteristic.objects.get(
                field_type=field_type,
                modification=self)
        except models.ObjectDoesNotExist:
            return None


# After creation Modification we must create characteristics and set null values
@receiver(signals.post_save, sender=Modification)
def constructor_modification(instance, **kwargs):
    if kwargs.get('created'):
        fields = instance.item.category.fieldtype_set.all()
        for field in fields:
            p = Characteristic(field_type=field, modification=instance, value=None)
            p.save()
    return None


# Type of field
class FieldType(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='Системное имя',
        validators=[validators.RegexValidator(
            regex=r'^[a-zA-Z0-9_]+$',
            message="Only ascii characters can be used")])
    title = models.CharField(
        max_length=50,
        verbose_name='Имя')
    category = models.ForeignKey(Category)
    typeName = models.CharField('type', max_length=50, choices=(
        ('integer', 'Int'),
        ('string', 'String'),
        ('float', 'Float')),
        null=True)
    unit = models.CharField(
        max_length=30,
        verbose_name='Единицы измерения',
        null=True,
        blank=True)
    priority = models.IntegerField(
        default=0,
        verbose_name='Приоритет')

    def __str__(self):
        return self.category.name + ' - ' + self.title


# After FieldType creation we must create characteristic and set null value
# for all modifications which are in the same category as FieldType.
@receiver(signals.post_save, sender=FieldType)
def constructor_fieldtype(instance, **kwargs):
    if kwargs.get('created'):
        items = instance.category.item_set.all()
        for item in items:
            modifications = item.modification_set.all()
            for modification in modifications:
                new_characteristic = Characteristic(field_type=instance, modification=modification)
                new_characteristic.save()
    return None


# Characteristic is used to connect modification, field_type and value
class Characteristic(models.Model):
    modification = models.ForeignKey(Modification)
    field_type = models.ForeignKey(FieldType)
    value = models.CharField(
        max_length=5000,
        null=True,
        verbose_name='Значение')

    def __str__(self):
        return self.field_type.name

    def title(self):
        return self.field_type.title

    def unit(self):
        return self.field_type.unit


# Price for catalog
class Price(models.Model):
    file = models.FileField(
        upload_to='files')
    label = models.CharField(
        max_length=50,
        default="")

adrian/store/cart/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.utils.safestring import mark_safe
from phonenumber_field.formfields import PhoneNumberField

from store.cart import widgets


class CheckoutForm(forms.Form):
    address = forms.CharField(label='Адрес', max_length=100, widget=widgets.AddressWidget())
    phone = PhoneNumberField(label='Номер телефона')
    first_name = forms.CharField(label='Имя', max_length=30)
    last_name = forms.CharField(label='Фамилия', max_length=30)
    captcha = ReCaptchaField(label='Вы человек?')
    error_css_class = 'error'

adrian/contacts/views.py
__author__ = 'Dmitriy'
from django.shortcuts import render


def contacts(request):
    return render(request, 'contacts/contacts.html')

adrian/store/cart/views.py
import threading

from django.shortcuts import render
from django.http.response import HttpResponseForbidden

from store.cart import apps as cart_settings
from . import utils
from store.cart import forms
from store.catalog import models as catalog_models
from django.views.generic.base import ContextMixin
from django.views.generic import FormView, TemplateView, View


def cart_preview(request):
    if request.method == 'GET' and request.is_ajax():
        products = utils.Cart.parse_from_request(request)
        return render(request, 'store/cart/render_cart/preview.html',
                      {'products': products,
                       'render_toolbox': True})
    return HttpResponseForbidden(request)


class ProductsInCartMixin(View):
    """
    CBV builds ProductsCart from request
    """
    def get_products_cart(self):
        return utils.Cart.parse_from_request(self.request)

    def dispatch(self, request, *args, **kwargs):
        self.products_cart = self.get_products_cart()
        return super(ProductsInCartMixin, self).dispatch(request, *args, **kwargs)


class CheckoutView(ProductsInCartMixin, FormView):
    template_name = 'store/cart/checkout/checkout.html'
    success_url = 'checkout/success'
    form_class = forms.CheckoutForm

    def get_context_data(self, **kwargs):
        kwargs['products'] = self.products_cart
        return super(CheckoutView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        user_data = {}
        for field in form.visible_fields():
            user_data[field.label] = form.cleaned_data[field.name]
        utils.notify_about_checkout(user_data, self.products_cart)
        return super(CheckoutView, self).form_valid(form)


class CheckoutSuccessView(ProductsInCartMixin, TemplateView):
    template_name = 'store/cart/checkout/checkout_success.html'

    def render_to_response(self, context, **response_kwargs):
        response = super(CheckoutSuccessView, self).render_to_response(context, **response_kwargs)
        utils.Cart.clear_in_response(response)
        return response

    def get_context_data(self, **kwargs):
        kwargs['products'] = self.products_cart
        return super(CheckoutSuccessView, self).get_context_data(**kwargs)

adrian/store/catalog/views.py
__author__ = 'Dmitriy'
from django.apps import apps
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from . import utils

from store.catalog import models


class ItemListView(ListView):
    """
    View with all items in category
    """
    model = models.Item
    template_name = 'store/catalog/items_in_category.html'

    def get_queryset(self):
        self.category = models.Category.objects.get(pk=self.kwargs['category_id'])
        return models.Item.objects.filter(category=self.category).prefetch_related('itemimage_set')

    def get_context_data(self, **kwargs):
        context = super(ItemListView, self).get_context_data(**kwargs)
        context['items'] = self.object_list
        context['category'] = self.category
        context['render_cart'] = apps.is_installed('store.cart')
        return context


class ItemDetailView(DetailView):
    """
    View for single item
    """
    model = models.Item
    template_name = "store/catalog/item_page.html"

    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        item = self.object
        context['item'] = item
        context['table'] = utils.CharacteristicsTable(item)
        context['selected_modifications'] = self.request.GET.getlist('modification')
        context['render_cart'] = apps.is_installed('store.cart')
        return context

adrian/templates/slideshows/render.html
{% comment %}
    Render slideshow
    slideshow - models.Slideshow object
{% endcomment %}


<script type='text/javascript' src = '/static/js/lib/jquery/jquery-2.1.3.min.js'></script>
<script type="text/javascript" src= '/static/adrian/scripts/jssor.slider.mini.js'></script>
<script>
    jQuery(document).ready(function ($) {

            var _SlideshowTransitions = [
            //Fade
            { $Duration: 1200, $Opacity: 2 }
            ];

            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlaySteps: 1,                                  //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
                $AutoPlayInterval: 3000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $PauseOnHover: 1,                               //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

                //$ArrowKeyNavigation: true,   			            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20
                //$SlideWidth: 700,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
                //$SlideHeight: 530,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
                $SlideSpacing: 0, 					                //[Optional] Space between each slide in pixels, default value is 0
                $DisplayPieces: 1,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                $ParkingPosition: 0,                                //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

                $SlideshowOptions: {                                //[Optional] Options to specify and enable slideshow or not
                    $Class: $JssorSlideshowRunner$,                 //[Required] Class to create instance of slideshow
                    $Transitions: _SlideshowTransitions,            //[Required] An array of slideshow transitions to play slideshow
                    $TransitionsOrder: 1,                           //[Optional] The way to choose transition to play slide, 1 Sequence, 0 Random
                    $ShowLink: true                                    //[Optional] Whether to bring slide link on top of the slider when slideshow is running, default value is false
                },

                $BulletNavigatorOptions: {                                //[Optional] Options to specify and enable navigator or not
                    $Class: $JssorBulletNavigator$,                       //[Required] Class to create navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 1,                                 //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1
                    $Lanes: 1,                                      //[Optional] Specify lanes to arrange items, default value is 1
                    $SpacingX: 10,                                   //[Optional] Horizontal space between each item in pixel, default value is 0
                    $SpacingY: 10,                                   //[Optional] Vertical space between each item in pixel, default value is 0
                    $Orientation: 1                                 //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
                },

                $ArrowNavigatorOptions: {
                    $Class: $JssorArrowNavigator$,              //[Requried] Class to create arrow navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                }
            };
            var jssor_slider1 = new $JssorSlider$("slider_container", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$ScaleWidth(Math.min(parentWidth, 700));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
</script>

<div id="slider_container" style="width: 700px; height: 530px; position: relative; overflow: hidden; ">

    <div u="slides" style="position: absolute; left: 0; top: 0; width: 700px; height: 530px;">
        {% load thumbnail %}
        {% for slide in slideshow.slide_set.all %}
            <div>
                <img u="image" src="{{ slide.image|thumbnail_url:'slideshow' }}" alt="" />
            </div>
        {% endfor %}
    </div>
    <style>
            /* jssor slider bullet navigator skin 05 css */
            /*
            .jssorb05 div           (normal)
            .jssorb05 div:hover     (normal mouseover)
            .jssorb05 .av           (active)
            .jssorb05 .av:hover     (active mouseover)
            .jssorb05 .dn           (mousedown)
            */
            .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
                background: url('/static/adrian/images/slideshow_skin/style1.png') no-repeat;
                overflow: hidden;
                cursor: pointer;
            }

            .jssorb05 div {
                background-position: -7px -7px;
            }

                .jssorb05 div:hover, .jssorb05 .av:hover {
                    background-position: -37px -7px;
                }

            .jssorb05 .av {
                background-position: -67px -7px;
            }

            .jssorb05 .dn, .jssorb05 .dn:hover {
                background-position: -97px -7px;
            }
    </style>

    <div u="navigator" class="jssorb05" style="position: absolute; bottom: 16px; right: 6px;">
            <!-- bullet navigator item prototype -->
            <div u="prototype" style="POSITION: absolute; WIDTH: 16px; HEIGHT: 16px;"></div>
    </div>
</div>
</div>